---
abstract: 'Parse and analyse dpkg log files'
author:
  - 'Patrick Schoenfeld <schoenfeld@debian.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DPKG-Log
no_index:
  directory:
    - examples
    - inc
    - t
    - tools
requires:
  DateTime: 0
  DateTime::Format::Strptime: 0
  DateTime::TimeZone: 0
  Params::Validate: 0
  perl: 5.10.0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
